# ===============================================================================
# VAGRANTFILE - Faky Faky Social Engineering Website
# ===============================================================================
#
# PROJECT DETAILS:
# ----------------
# Created by: mguirao
# Date: 2026-01-02
# Time: Current session
#
# ORIGINAL PROMPT:
# ----------------
# Create a Vagrantfile using the Linux Alpine distro, with the latest Apache
# http server. Make sure the webserver can be reached on a LAN by using the
# internal domain name fakyfakywebsite.com. Maybe you will need to modify the
# host file in order to achieve this. Once you make sure that the http service
# is running and accessible using the internal domain name, also create a basic
# webpage using HTML, CSS and Javascript that presents to the user a login form
# to the "Faky Faky Website" where users can learn all about Social Engineering.
# This VM should have assigned a local IP address so it can be reached by a LAN
# IP address. Save this prompt as part of the documentation of the Vagrantfile,
# along with my username, date and time. If you have any question, ask me.
# Include a couple of images on the webpage related to Social Engineering.
#
# CONFIGURATION:
# --------------
# VM IP Address: 192.168.56.10
# Domain Name: fakyfakywebsite.com
# OS: Alpine Linux (generic/alpine316)
# Web Server: Apache HTTP Server (latest)
#
# SETUP INSTRUCTIONS:
# -------------------
# 1. Run: vagrant up
# 2. Add the following line to your HOST machine's hosts file:
#
#    On Linux/Mac: /etc/hosts
#    On Windows: C:\Windows\System32\drivers\etc\hosts
#
#    Add this line:
#    192.168.56.10  fakyfakywebsite.com
#
# 3. Access the website at: http://fakyfakywebsite.com
#
# USEFUL COMMANDS:
# ----------------
# vagrant up       - Start the VM
# vagrant halt     - Stop the VM
# vagrant destroy  - Delete the VM
# vagrant ssh      - SSH into the VM
# vagrant reload   - Restart the VM
#
# ===============================================================================

Vagrant.configure("2") do |config|
  # Alpine Linux base box
  config.vm.box = "generic/alpine316"

  # VM hostname
  config.vm.hostname = "fakyfakywebsite"

  # Configure private network with static IP
  config.vm.network "private_network", ip: "192.168.56.10"

  # Forward port 80 (optional, since we're using private network)
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # VM provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "FakyFakyWebsite_SocialEngineering"
    vb.memory = "512"
    vb.cpus = 1
  end

  # Sync folder for web content
  config.vm.synced_folder ".", "/vagrant"

  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    echo "========================================"
    echo "Provisioning Faky Faky Website VM..."
    echo "========================================"

    # Update package index
    apk update

    # Install Apache
    echo "Installing Apache HTTP Server..."
    apk add apache2

    # Create document root
    mkdir -p /var/www/fakyfakywebsite.com/public_html

    # Copy website files from shared folder
    if [ -f /vagrant/www/index.html ]; then
      cp -r /vagrant/www/* /var/www/fakyfakywebsite.com/public_html/
      echo "Website files copied successfully"
    else
      echo "Warning: Website files not found in /vagrant/www/"
    fi

    # Set permissions
    chown -R apache:apache /var/www/fakyfakywebsite.com
    chmod -R 755 /var/www/fakyfakywebsite.com

    # Configure Apache virtual host
    cat > /etc/apache2/conf.d/fakyfakywebsite.conf <<EOF
<VirtualHost *:80>
    ServerName fakyfakywebsite.com
    ServerAlias www.fakyfakywebsite.com
    DocumentRoot /var/www/fakyfakywebsite.com/public_html

    <Directory /var/www/fakyfakywebsite.com/public_html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/log/apache2/fakyfakywebsite-error.log
    CustomLog /var/log/apache2/fakyfakywebsite-access.log combined
</VirtualHost>
EOF

    # Enable Apache to start on boot
    rc-update add apache2 default

    # Start Apache service
    service apache2 start

    # Display status
    echo "========================================"
    echo "Provisioning Complete!"
    echo "========================================"
    echo "Apache Status:"
    rc-status | grep apache2
    echo ""
    echo "Access your website at:"
    echo "  http://fakyfakywebsite.com"
    echo "  or http://192.168.56.10"
    echo ""
    echo "Remember to add to your HOST machine's hosts file:"
    echo "  192.168.56.10  fakyfakywebsite.com"
    echo "========================================"
  SHELL
end
